<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Master\Geografis\Regions;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['id' => '11', 'parent' => '0', 'name' => 'ACEH', 'created_by' => '1'],
            ['id' => '12', 'parent' => '0', 'name' => 'SUMATERA UTARA', 'created_by' => '1'],
            ['id' => '13', 'parent' => '0', 'name' => 'SUMATERA BARAT', 'created_by' => '1'],
            ['id' => '14', 'parent' => '0', 'name' => 'RIAU', 'created_by' => '1'],
            ['id' => '15', 'parent' => '0', 'name' => 'JAMBI', 'created_by' => '1'],
            ['id' => '16', 'parent' => '0', 'name' => 'SUMATERA SELATAN', 'created_by' => '1'],
            ['id' => '17', 'parent' => '0', 'name' => 'BENGKULU', 'created_by' => '1'],
            ['id' => '18', 'parent' => '0', 'name' => 'LAMPUNG', 'created_by' => '1'],
            ['id' => '19', 'parent' => '0', 'name' => 'KEPULAUAN BANGKA BELITUNG', 'created_by' => '1'],
            ['id' => '21', 'parent' => '0', 'name' => 'KEPULAUAN RIAU', 'created_by' => '1'],
            ['id' => '31', 'parent' => '0', 'name' => 'DKI JAKARTA', 'created_by' => '1'],
            ['id' => '32', 'parent' => '0', 'name' => 'JAWA BARAT', 'created_by' => '1'],
            ['id' => '33', 'parent' => '0', 'name' => 'JAWA TENGAH', 'created_by' => '1'],
            ['id' => '34', 'parent' => '0', 'name' => 'DI YOGYAKARTA', 'created_by' => '1'],
            ['id' => '35', 'parent' => '0', 'name' => 'JAWA TIMUR', 'created_by' => '1'],
            ['id' => '36', 'parent' => '0', 'name' => 'BANTEN', 'created_by' => '1'],
            ['id' => '51', 'parent' => '0', 'name' => 'BALI', 'created_by' => '1'],
            ['id' => '52', 'parent' => '0', 'name' => 'NUSA TENGGARA BARAT', 'created_by' => '1'],
            ['id' => '53', 'parent' => '0', 'name' => 'NUSA TENGGARA TIMUR', 'created_by' => '1'],
            ['id' => '61', 'parent' => '0', 'name' => 'KALIMANTAN BARAT', 'created_by' => '1'],
            ['id' => '62', 'parent' => '0', 'name' => 'KALIMANTAN TENGAH', 'created_by' => '1'],
            ['id' => '63', 'parent' => '0', 'name' => 'KALIMANTAN SELATAN', 'created_by' => '1'],
            ['id' => '64', 'parent' => '0', 'name' => 'KALIMANTAN TIMUR', 'created_by' => '1'],
            ['id' => '65', 'parent' => '0', 'name' => 'KALIMANTAN UTARA', 'created_by' => '1'],
            ['id' => '71', 'parent' => '0', 'name' => 'SULAWESI UTARA', 'created_by' => '1'],
            ['id' => '72', 'parent' => '0', 'name' => 'SULAWESI TENGAH', 'created_by' => '1'],
            ['id' => '73', 'parent' => '0', 'name' => 'SULAWESI SELATAN', 'created_by' => '1'],
            ['id' => '74', 'parent' => '0', 'name' => 'SULAWESI TENGGARA', 'created_by' => '1'],
            ['id' => '75', 'parent' => '0', 'name' => 'GORONTALO', 'created_by' => '1'],
            ['id' => '76', 'parent' => '0', 'name' => 'SULAWESI BARAT', 'created_by' => '1'],
            ['id' => '81', 'parent' => '0', 'name' => 'MALUKU', 'created_by' => '1'],
            ['id' => '82', 'parent' => '0', 'name' => 'MALUKU UTARA', 'created_by' => '1'],
            ['id' => '91', 'parent' => '0', 'name' => 'PAPUA BARAT', 'created_by' => '1'],
            ['id' => '94', 'parent' => '0', 'name' => 'PAPUA', 'created_by' => '1'],
            ['id' => '1101', 'parent' => '11', 'name' => 'KABUPATEN SIMEULUE', 'created_by' => '1'],
            ['id' => '1102', 'parent' => '11', 'name' => 'KABUPATEN ACEH SINGKIL', 'created_by' => '1'],
            ['id' => '1103', 'parent' => '11', 'name' => 'KABUPATEN ACEH SELATAN', 'created_by' => '1'],
            ['id' => '1104', 'parent' => '11', 'name' => 'KABUPATEN ACEH TENGGARA', 'created_by' => '1'],
            ['id' => '1105', 'parent' => '11', 'name' => 'KABUPATEN ACEH TIMUR', 'created_by' => '1'],
            ['id' => '1106', 'parent' => '11', 'name' => 'KABUPATEN ACEH TENGAH', 'created_by' => '1'],
            ['id' => '1107', 'parent' => '11', 'name' => 'KABUPATEN ACEH BARAT', 'created_by' => '1'],
            ['id' => '1108', 'parent' => '11', 'name' => 'KABUPATEN ACEH BESAR', 'created_by' => '1'],
            ['id' => '1109', 'parent' => '11', 'name' => 'KABUPATEN PIDIE', 'created_by' => '1'],
            ['id' => '1110', 'parent' => '11', 'name' => 'KABUPATEN BIREUEN', 'created_by' => '1'],
            ['id' => '1111', 'parent' => '11', 'name' => 'KABUPATEN ACEH UTARA', 'created_by' => '1'],
            ['id' => '1112', 'parent' => '11', 'name' => 'KABUPATEN ACEH BARAT DAYA', 'created_by' => '1'],
            ['id' => '1113', 'parent' => '11', 'name' => 'KABUPATEN GAYO LUES', 'created_by' => '1'],
            ['id' => '1114', 'parent' => '11', 'name' => 'KABUPATEN ACEH TAMIANG', 'created_by' => '1'],
            ['id' => '1115', 'parent' => '11', 'name' => 'KABUPATEN NAGAN RAYA', 'created_by' => '1'],
            ['id' => '1116', 'parent' => '11', 'name' => 'KABUPATEN ACEH JAYA', 'created_by' => '1'],
            ['id' => '1117', 'parent' => '11', 'name' => 'KABUPATEN BENER MERIAH', 'created_by' => '1'],
            ['id' => '1118', 'parent' => '11', 'name' => 'KABUPATEN PIDIE JAYA', 'created_by' => '1'],
            ['id' => '1171', 'parent' => '11', 'name' => 'KOTA BANDA ACEH', 'created_by' => '1'],
            ['id' => '1172', 'parent' => '11', 'name' => 'KOTA SABANG', 'created_by' => '1'],
            ['id' => '1173', 'parent' => '11', 'name' => 'KOTA LANGSA', 'created_by' => '1'],
            ['id' => '1174', 'parent' => '11', 'name' => 'KOTA LHOKSEUMAWE', 'created_by' => '1'],
            ['id' => '1175', 'parent' => '11', 'name' => 'KOTA SUBULUSSALAM', 'created_by' => '1'],
            ['id' => '1201', 'parent' => '12', 'name' => 'KABUPATEN NIAS', 'created_by' => '1'],
            ['id' => '1202', 'parent' => '12', 'name' => 'KABUPATEN MANDAILING NATAL', 'created_by' => '1'],
            ['id' => '1203', 'parent' => '12', 'name' => 'KABUPATEN TAPANULI SELATAN', 'created_by' => '1'],
            ['id' => '1204', 'parent' => '12', 'name' => 'KABUPATEN TAPANULI TENGAH', 'created_by' => '1'],
            ['id' => '1205', 'parent' => '12', 'name' => 'KABUPATEN TAPANULI UTARA', 'created_by' => '1'],
            ['id' => '1206', 'parent' => '12', 'name' => 'KABUPATEN TOBA SAMOSIR', 'created_by' => '1'],
            ['id' => '1207', 'parent' => '12', 'name' => 'KABUPATEN LABUHAN BATU', 'created_by' => '1'],
            ['id' => '1208', 'parent' => '12', 'name' => 'KABUPATEN ASAHAN', 'created_by' => '1'],
            ['id' => '1209', 'parent' => '12', 'name' => 'KABUPATEN SIMALUNGUN', 'created_by' => '1'],
            ['id' => '1210', 'parent' => '12', 'name' => 'KABUPATEN DAIRI', 'created_by' => '1'],
            ['id' => '1211', 'parent' => '12', 'name' => 'KABUPATEN KARO', 'created_by' => '1'],
            ['id' => '1212', 'parent' => '12', 'name' => 'KABUPATEN DELI SERDANG', 'created_by' => '1'],
            ['id' => '1213', 'parent' => '12', 'name' => 'KABUPATEN LANGKAT', 'created_by' => '1'],
            ['id' => '1214', 'parent' => '12', 'name' => 'KABUPATEN NIAS SELATAN', 'created_by' => '1'],
            ['id' => '1215', 'parent' => '12', 'name' => 'KABUPATEN HUMBANG HASUNDUTAN', 'created_by' => '1'],
            ['id' => '1216', 'parent' => '12', 'name' => 'KABUPATEN PAKPAK BHARAT', 'created_by' => '1'],
            ['id' => '1217', 'parent' => '12', 'name' => 'KABUPATEN SAMOSIR', 'created_by' => '1'],
            ['id' => '1218', 'parent' => '12', 'name' => 'KABUPATEN SERDANG BEDAGAI', 'created_by' => '1'],
            ['id' => '1219', 'parent' => '12', 'name' => 'KABUPATEN BATU BARA', 'created_by' => '1'],
            ['id' => '1220', 'parent' => '12', 'name' => 'KABUPATEN PADANG LAWAS UTARA', 'created_by' => '1'],
            ['id' => '1221', 'parent' => '12', 'name' => 'KABUPATEN PADANG LAWAS', 'created_by' => '1'],
            ['id' => '1222', 'parent' => '12', 'name' => 'KABUPATEN LABUHAN BATU SELATAN', 'created_by' => '1'],
            ['id' => '1223', 'parent' => '12', 'name' => 'KABUPATEN LABUHAN BATU UTARA', 'created_by' => '1'],
            ['id' => '1224', 'parent' => '12', 'name' => 'KABUPATEN NIAS UTARA', 'created_by' => '1'],
            ['id' => '1225', 'parent' => '12', 'name' => 'KABUPATEN NIAS BARAT', 'created_by' => '1'],
            ['id' => '1271', 'parent' => '12', 'name' => 'KOTA SIBOLGA', 'created_by' => '1'],
            ['id' => '1272', 'parent' => '12', 'name' => 'KOTA TANJUNG BALAI', 'created_by' => '1'],
            ['id' => '1273', 'parent' => '12', 'name' => 'KOTA PEMATANG SIANTAR', 'created_by' => '1'],
            ['id' => '1274', 'parent' => '12', 'name' => 'KOTA TEBING TINGGI', 'created_by' => '1'],
            ['id' => '1275', 'parent' => '12', 'name' => 'KOTA MEDAN', 'created_by' => '1'],
            ['id' => '1276', 'parent' => '12', 'name' => 'KOTA BINJAI', 'created_by' => '1'],
            ['id' => '1277', 'parent' => '12', 'name' => 'KOTA PADANGSIDIMPUAN', 'created_by' => '1'],
            ['id' => '1278', 'parent' => '12', 'name' => 'KOTA GUNUNGSITOLI', 'created_by' => '1'],
            ['id' => '1301', 'parent' => '13', 'name' => 'KABUPATEN KEPULAUAN MENTAWAI', 'created_by' => '1'],
            ['id' => '1302', 'parent' => '13', 'name' => 'KABUPATEN PESISIR SELATAN', 'created_by' => '1'],
            ['id' => '1303', 'parent' => '13', 'name' => 'KABUPATEN SOLOK', 'created_by' => '1'],
            ['id' => '1304', 'parent' => '13', 'name' => 'KABUPATEN SIJUNJUNG', 'created_by' => '1'],
            ['id' => '1305', 'parent' => '13', 'name' => 'KABUPATEN TANAH DATAR', 'created_by' => '1'],
            ['id' => '1306', 'parent' => '13', 'name' => 'KABUPATEN PADANG PARIAMAN', 'created_by' => '1'],
            ['id' => '1307', 'parent' => '13', 'name' => 'KABUPATEN AGAM', 'created_by' => '1'],
            ['id' => '1308', 'parent' => '13', 'name' => 'KABUPATEN LIMA PULUH KOTA', 'created_by' => '1'],
            ['id' => '1309', 'parent' => '13', 'name' => 'KABUPATEN PASAMAN', 'created_by' => '1'],
            ['id' => '1310', 'parent' => '13', 'name' => 'KABUPATEN SOLOK SELATAN', 'created_by' => '1'],
            ['id' => '1311', 'parent' => '13', 'name' => 'KABUPATEN DHARMASRAYA', 'created_by' => '1'],
            ['id' => '1312', 'parent' => '13', 'name' => 'KABUPATEN PASAMAN BARAT', 'created_by' => '1'],
            ['id' => '1371', 'parent' => '13', 'name' => 'KOTA PADANG', 'created_by' => '1'],
            ['id' => '1372', 'parent' => '13', 'name' => 'KOTA SOLOK', 'created_by' => '1'],
            ['id' => '1373', 'parent' => '13', 'name' => 'KOTA SAWAH LUNTO', 'created_by' => '1'],
            ['id' => '1374', 'parent' => '13', 'name' => 'KOTA PADANG PANJANG', 'created_by' => '1'],
            ['id' => '1375', 'parent' => '13', 'name' => 'KOTA BUKITTINGGI', 'created_by' => '1'],
            ['id' => '1376', 'parent' => '13', 'name' => 'KOTA PAYAKUMBUH', 'created_by' => '1'],
            ['id' => '1377', 'parent' => '13', 'name' => 'KOTA PARIAMAN', 'created_by' => '1'],
            ['id' => '1401', 'parent' => '14', 'name' => 'KABUPATEN KUANTAN SINGINGI', 'created_by' => '1'],
            ['id' => '1402', 'parent' => '14', 'name' => 'KABUPATEN INDRAGIRI HULU', 'created_by' => '1'],
            ['id' => '1403', 'parent' => '14', 'name' => 'KABUPATEN INDRAGIRI HILIR', 'created_by' => '1'],
            ['id' => '1404', 'parent' => '14', 'name' => 'KABUPATEN PELALAWAN', 'created_by' => '1'],
            ['id' => '1405', 'parent' => '14', 'name' => 'KABUPATEN S I A K', 'created_by' => '1'],
            ['id' => '1406', 'parent' => '14', 'name' => 'KABUPATEN KAMPAR', 'created_by' => '1'],
            ['id' => '1407', 'parent' => '14', 'name' => 'KABUPATEN ROKAN HULU', 'created_by' => '1'],
            ['id' => '1408', 'parent' => '14', 'name' => 'KABUPATEN BENGKALIS', 'created_by' => '1'],
            ['id' => '1409', 'parent' => '14', 'name' => 'KABUPATEN ROKAN HILIR', 'created_by' => '1'],
            ['id' => '1410', 'parent' => '14', 'name' => 'KABUPATEN KEPULAUAN MERANTI', 'created_by' => '1'],
            ['id' => '1471', 'parent' => '14', 'name' => 'KOTA PEKANBARU', 'created_by' => '1'],
            ['id' => '1473', 'parent' => '14', 'name' => 'KOTA D U M A I', 'created_by' => '1'],
            ['id' => '1501', 'parent' => '15', 'name' => 'KABUPATEN KERINCI', 'created_by' => '1'],
            ['id' => '1502', 'parent' => '15', 'name' => 'KABUPATEN MERANGIN', 'created_by' => '1'],
            ['id' => '1503', 'parent' => '15', 'name' => 'KABUPATEN SAROLANGUN', 'created_by' => '1'],
            ['id' => '1504', 'parent' => '15', 'name' => 'KABUPATEN BATANG HARI', 'created_by' => '1'],
            ['id' => '1505', 'parent' => '15', 'name' => 'KABUPATEN MUARO JAMBI', 'created_by' => '1'],
            ['id' => '1506', 'parent' => '15', 'name' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'created_by' => '1'],
            ['id' => '1507', 'parent' => '15', 'name' => 'KABUPATEN TANJUNG JABUNG BARAT', 'created_by' => '1'],
            ['id' => '1508', 'parent' => '15', 'name' => 'KABUPATEN TEBO', 'created_by' => '1'],
            ['id' => '1509', 'parent' => '15', 'name' => 'KABUPATEN BUNGO', 'created_by' => '1'],
            ['id' => '1571', 'parent' => '15', 'name' => 'KOTA JAMBI', 'created_by' => '1'],
            ['id' => '1572', 'parent' => '15', 'name' => 'KOTA SUNGAI PENUH', 'created_by' => '1'],
            ['id' => '1601', 'parent' => '16', 'name' => 'KABUPATEN OGAN KOMERING ULU', 'created_by' => '1'],
            ['id' => '1602', 'parent' => '16', 'name' => 'KABUPATEN OGAN KOMERING ILIR', 'created_by' => '1'],
            ['id' => '1603', 'parent' => '16', 'name' => 'KABUPATEN MUARA ENIM', 'created_by' => '1'],
            ['id' => '1604', 'parent' => '16', 'name' => 'KABUPATEN LAHAT', 'created_by' => '1'],
            ['id' => '1605', 'parent' => '16', 'name' => 'KABUPATEN MUSI RAWAS', 'created_by' => '1'],
            ['id' => '1606', 'parent' => '16', 'name' => 'KABUPATEN MUSI BANYUASIN', 'created_by' => '1'],
            ['id' => '1607', 'parent' => '16', 'name' => 'KABUPATEN BANYU ASIN', 'created_by' => '1'],
            ['id' => '1608', 'parent' => '16', 'name' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'created_by' => '1'],
            ['id' => '1609', 'parent' => '16', 'name' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'created_by' => '1'],
            ['id' => '1610', 'parent' => '16', 'name' => 'KABUPATEN OGAN ILIR', 'created_by' => '1'],
            ['id' => '1611', 'parent' => '16', 'name' => 'KABUPATEN EMPAT LAWANG', 'created_by' => '1'],
            ['id' => '1612', 'parent' => '16', 'name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'created_by' => '1'],
            ['id' => '1613', 'parent' => '16', 'name' => 'KABUPATEN MUSI RAWAS UTARA', 'created_by' => '1'],
            ['id' => '1671', 'parent' => '16', 'name' => 'KOTA PALEMBANG', 'created_by' => '1'],
            ['id' => '1672', 'parent' => '16', 'name' => 'KOTA PRABUMULIH', 'created_by' => '1'],
            ['id' => '1673', 'parent' => '16', 'name' => 'KOTA PAGAR ALAM', 'created_by' => '1'],
            ['id' => '1674', 'parent' => '16', 'name' => 'KOTA LUBUKLINGGAU', 'created_by' => '1'],
            ['id' => '1701', 'parent' => '17', 'name' => 'KABUPATEN BENGKULU SELATAN', 'created_by' => '1'],
            ['id' => '1702', 'parent' => '17', 'name' => 'KABUPATEN REJANG LEBONG', 'created_by' => '1'],
            ['id' => '1703', 'parent' => '17', 'name' => 'KABUPATEN BENGKULU UTARA', 'created_by' => '1'],
            ['id' => '1704', 'parent' => '17', 'name' => 'KABUPATEN KAUR', 'created_by' => '1'],
            ['id' => '1705', 'parent' => '17', 'name' => 'KABUPATEN SELUMA', 'created_by' => '1'],
            ['id' => '1706', 'parent' => '17', 'name' => 'KABUPATEN MUKOMUKO', 'created_by' => '1'],
            ['id' => '1707', 'parent' => '17', 'name' => 'KABUPATEN LEBONG', 'created_by' => '1'],
            ['id' => '1708', 'parent' => '17', 'name' => 'KABUPATEN KEPAHIANG', 'created_by' => '1'],
            ['id' => '1709', 'parent' => '17', 'name' => 'KABUPATEN BENGKULU TENGAH', 'created_by' => '1'],
            ['id' => '1771', 'parent' => '17', 'name' => 'KOTA BENGKULU', 'created_by' => '1'],
            ['id' => '1801', 'parent' => '18', 'name' => 'KABUPATEN LAMPUNG BARAT', 'created_by' => '1'],
            ['id' => '1802', 'parent' => '18', 'name' => 'KABUPATEN TANGGAMUS', 'created_by' => '1'],
            ['id' => '1803', 'parent' => '18', 'name' => 'KABUPATEN LAMPUNG SELATAN', 'created_by' => '1'],
            ['id' => '1804', 'parent' => '18', 'name' => 'KABUPATEN LAMPUNG TIMUR', 'created_by' => '1'],
            ['id' => '1805', 'parent' => '18', 'name' => 'KABUPATEN LAMPUNG TENGAH', 'created_by' => '1'],
            ['id' => '1806', 'parent' => '18', 'name' => 'KABUPATEN LAMPUNG UTARA', 'created_by' => '1'],
            ['id' => '1807', 'parent' => '18', 'name' => 'KABUPATEN WAY KANAN', 'created_by' => '1'],
            ['id' => '1808', 'parent' => '18', 'name' => 'KABUPATEN TULANGBAWANG', 'created_by' => '1'],
            ['id' => '1809', 'parent' => '18', 'name' => 'KABUPATEN PESAWARAN', 'created_by' => '1'],
            ['id' => '1810', 'parent' => '18', 'name' => 'KABUPATEN PRINGSEWU', 'created_by' => '1'],
            ['id' => '1811', 'parent' => '18', 'name' => 'KABUPATEN MESUJI', 'created_by' => '1'],
            ['id' => '1812', 'parent' => '18', 'name' => 'KABUPATEN TULANG BAWANG BARAT', 'created_by' => '1'],
            ['id' => '1813', 'parent' => '18', 'name' => 'KABUPATEN PESISIR BARAT', 'created_by' => '1'],
            ['id' => '1871', 'parent' => '18', 'name' => 'KOTA BANDAR LAMPUNG', 'created_by' => '1'],
            ['id' => '1872', 'parent' => '18', 'name' => 'KOTA METRO', 'created_by' => '1'],
            ['id' => '1901', 'parent' => '19', 'name' => 'KABUPATEN BANGKA', 'created_by' => '1'],
            ['id' => '1902', 'parent' => '19', 'name' => 'KABUPATEN BELITUNG', 'created_by' => '1'],
            ['id' => '1903', 'parent' => '19', 'name' => 'KABUPATEN BANGKA BARAT', 'created_by' => '1'],
            ['id' => '1904', 'parent' => '19', 'name' => 'KABUPATEN BANGKA TENGAH', 'created_by' => '1'],
            ['id' => '1905', 'parent' => '19', 'name' => 'KABUPATEN BANGKA SELATAN', 'created_by' => '1'],
            ['id' => '1906', 'parent' => '19', 'name' => 'KABUPATEN BELITUNG TIMUR', 'created_by' => '1'],
            ['id' => '1971', 'parent' => '19', 'name' => 'KOTA PANGKAL PINANG', 'created_by' => '1'],
            ['id' => '2101', 'parent' => '21', 'name' => 'KABUPATEN KARIMUN', 'created_by' => '1'],
            ['id' => '2102', 'parent' => '21', 'name' => 'KABUPATEN BINTAN', 'created_by' => '1'],
            ['id' => '2103', 'parent' => '21', 'name' => 'KABUPATEN NATUNA', 'created_by' => '1'],
            ['id' => '2104', 'parent' => '21', 'name' => 'KABUPATEN LINGGA', 'created_by' => '1'],
            ['id' => '2105', 'parent' => '21', 'name' => 'KABUPATEN KEPULAUAN ANAMBAS', 'created_by' => '1'],
            ['id' => '2171', 'parent' => '21', 'name' => 'KOTA B A T A M', 'created_by' => '1'],
            ['id' => '2172', 'parent' => '21', 'name' => 'KOTA TANJUNG PINANG', 'created_by' => '1'],
            ['id' => '3101', 'parent' => '31', 'name' => 'KABUPATEN KEPULAUAN SERIBU', 'created_by' => '1'],
            ['id' => '3171', 'parent' => '31', 'name' => 'KOTA JAKARTA SELATAN', 'created_by' => '1'],
            ['id' => '3172', 'parent' => '31', 'name' => 'KOTA JAKARTA TIMUR', 'created_by' => '1'],
            ['id' => '3173', 'parent' => '31', 'name' => 'KOTA JAKARTA PUSAT', 'created_by' => '1'],
            ['id' => '3174', 'parent' => '31', 'name' => 'KOTA JAKARTA BARAT', 'created_by' => '1'],
            ['id' => '3175', 'parent' => '31', 'name' => 'KOTA JAKARTA UTARA', 'created_by' => '1'],
            ['id' => '3201', 'parent' => '32', 'name' => 'KABUPATEN BOGOR', 'created_by' => '1'],
            ['id' => '3202', 'parent' => '32', 'name' => 'KABUPATEN SUKABUMI', 'created_by' => '1'],
            ['id' => '3203', 'parent' => '32', 'name' => 'KABUPATEN CIANJUR', 'created_by' => '1'],
            ['id' => '3204', 'parent' => '32', 'name' => 'KABUPATEN BANDUNG', 'created_by' => '1'],
            ['id' => '3205', 'parent' => '32', 'name' => 'KABUPATEN GARUT', 'created_by' => '1'],
            ['id' => '3206', 'parent' => '32', 'name' => 'KABUPATEN TASIKMALAYA', 'created_by' => '1'],
            ['id' => '3207', 'parent' => '32', 'name' => 'KABUPATEN CIAMIS', 'created_by' => '1'],
            ['id' => '3208', 'parent' => '32', 'name' => 'KABUPATEN KUNINGAN', 'created_by' => '1'],
            ['id' => '3209', 'parent' => '32', 'name' => 'KABUPATEN CIREBON', 'created_by' => '1'],
            ['id' => '3210', 'parent' => '32', 'name' => 'KABUPATEN MAJALENGKA', 'created_by' => '1'],
            ['id' => '3211', 'parent' => '32', 'name' => 'KABUPATEN SUMEDANG', 'created_by' => '1'],
            ['id' => '3212', 'parent' => '32', 'name' => 'KABUPATEN INDRAMAYU', 'created_by' => '1'],
            ['id' => '3213', 'parent' => '32', 'name' => 'KABUPATEN SUBANG', 'created_by' => '1'],
            ['id' => '3214', 'parent' => '32', 'name' => 'KABUPATEN PURWAKARTA', 'created_by' => '1'],
            ['id' => '3215', 'parent' => '32', 'name' => 'KABUPATEN KARAWANG', 'created_by' => '1'],
            ['id' => '3216', 'parent' => '32', 'name' => 'KABUPATEN BEKASI', 'created_by' => '1'],
            ['id' => '3217', 'parent' => '32', 'name' => 'KABUPATEN BANDUNG BARAT', 'created_by' => '1'],
            ['id' => '3218', 'parent' => '32', 'name' => 'KABUPATEN PANGANDARAN', 'created_by' => '1'],
            ['id' => '3271', 'parent' => '32', 'name' => 'KOTA BOGOR', 'created_by' => '1'],
            ['id' => '3272', 'parent' => '32', 'name' => 'KOTA SUKABUMI', 'created_by' => '1'],
            ['id' => '3273', 'parent' => '32', 'name' => 'KOTA BANDUNG', 'created_by' => '1'],
            ['id' => '3274', 'parent' => '32', 'name' => 'KOTA CIREBON', 'created_by' => '1'],
            ['id' => '3275', 'parent' => '32', 'name' => 'KOTA BEKASI', 'created_by' => '1'],
            ['id' => '3276', 'parent' => '32', 'name' => 'KOTA DEPOK', 'created_by' => '1'],
            ['id' => '3277', 'parent' => '32', 'name' => 'KOTA CIMAHI', 'created_by' => '1'],
            ['id' => '3278', 'parent' => '32', 'name' => 'KOTA TASIKMALAYA', 'created_by' => '1'],
            ['id' => '3279', 'parent' => '32', 'name' => 'KOTA BANJAR', 'created_by' => '1'],
            ['id' => '3301', 'parent' => '33', 'name' => 'KABUPATEN CILACAP', 'created_by' => '1'],
            ['id' => '3302', 'parent' => '33', 'name' => 'KABUPATEN BANYUMAS', 'created_by' => '1'],
            ['id' => '3303', 'parent' => '33', 'name' => 'KABUPATEN PURBALINGGA', 'created_by' => '1'],
            ['id' => '3304', 'parent' => '33', 'name' => 'KABUPATEN BANJARNEGARA', 'created_by' => '1'],
            ['id' => '3305', 'parent' => '33', 'name' => 'KABUPATEN KEBUMEN', 'created_by' => '1'],
            ['id' => '3306', 'parent' => '33', 'name' => 'KABUPATEN PURWOREJO', 'created_by' => '1'],
            ['id' => '3307', 'parent' => '33', 'name' => 'KABUPATEN WONOSOBO', 'created_by' => '1'],
            ['id' => '3308', 'parent' => '33', 'name' => 'KABUPATEN MAGELANG', 'created_by' => '1'],
            ['id' => '3309', 'parent' => '33', 'name' => 'KABUPATEN BOYOLALI', 'created_by' => '1'],
            ['id' => '3310', 'parent' => '33', 'name' => 'KABUPATEN KLATEN', 'created_by' => '1'],
            ['id' => '3311', 'parent' => '33', 'name' => 'KABUPATEN SUKOHARJO', 'created_by' => '1'],
            ['id' => '3312', 'parent' => '33', 'name' => 'KABUPATEN WONOGIRI', 'created_by' => '1'],
            ['id' => '3313', 'parent' => '33', 'name' => 'KABUPATEN KARANGANYAR', 'created_by' => '1'],
            ['id' => '3314', 'parent' => '33', 'name' => 'KABUPATEN SRAGEN', 'created_by' => '1'],
            ['id' => '3315', 'parent' => '33', 'name' => 'KABUPATEN GROBOGAN', 'created_by' => '1'],
            ['id' => '3316', 'parent' => '33', 'name' => 'KABUPATEN BLORA', 'created_by' => '1'],
            ['id' => '3317', 'parent' => '33', 'name' => 'KABUPATEN REMBANG', 'created_by' => '1'],
            ['id' => '3318', 'parent' => '33', 'name' => 'KABUPATEN PATI', 'created_by' => '1'],
            ['id' => '3319', 'parent' => '33', 'name' => 'KABUPATEN KUDUS', 'created_by' => '1'],
            ['id' => '3320', 'parent' => '33', 'name' => 'KABUPATEN JEPARA', 'created_by' => '1'],
            ['id' => '3321', 'parent' => '33', 'name' => 'KABUPATEN DEMAK', 'created_by' => '1'],
            ['id' => '3322', 'parent' => '33', 'name' => 'KABUPATEN SEMARANG', 'created_by' => '1'],
            ['id' => '3323', 'parent' => '33', 'name' => 'KABUPATEN TEMANGGUNG', 'created_by' => '1'],
            ['id' => '3324', 'parent' => '33', 'name' => 'KABUPATEN KENDAL', 'created_by' => '1'],
            ['id' => '3325', 'parent' => '33', 'name' => 'KABUPATEN BATANG', 'created_by' => '1'],
            ['id' => '3326', 'parent' => '33', 'name' => 'KABUPATEN PEKALONGAN', 'created_by' => '1'],
            ['id' => '3327', 'parent' => '33', 'name' => 'KABUPATEN PEMALANG', 'created_by' => '1'],
            ['id' => '3328', 'parent' => '33', 'name' => 'KABUPATEN TEGAL', 'created_by' => '1'],
            ['id' => '3329', 'parent' => '33', 'name' => 'KABUPATEN BREBES', 'created_by' => '1'],
            ['id' => '3371', 'parent' => '33', 'name' => 'KOTA MAGELANG', 'created_by' => '1'],
            ['id' => '3372', 'parent' => '33', 'name' => 'KOTA SURAKARTA', 'created_by' => '1'],
            ['id' => '3373', 'parent' => '33', 'name' => 'KOTA SALATIGA', 'created_by' => '1'],
            ['id' => '3374', 'parent' => '33', 'name' => 'KOTA SEMARANG', 'created_by' => '1'],
            ['id' => '3375', 'parent' => '33', 'name' => 'KOTA PEKALONGAN', 'created_by' => '1'],
            ['id' => '3376', 'parent' => '33', 'name' => 'KOTA TEGAL', 'created_by' => '1'],
            ['id' => '3401', 'parent' => '34', 'name' => 'KABUPATEN KULON PROGO', 'created_by' => '1'],
            ['id' => '3402', 'parent' => '34', 'name' => 'KABUPATEN BANTUL', 'created_by' => '1'],
            ['id' => '3403', 'parent' => '34', 'name' => 'KABUPATEN GUNUNG KIDUL', 'created_by' => '1'],
            ['id' => '3404', 'parent' => '34', 'name' => 'KABUPATEN SLEMAN', 'created_by' => '1'],
            ['id' => '3471', 'parent' => '34', 'name' => 'KOTA YOGYAKARTA', 'created_by' => '1'],
            ['id' => '3501', 'parent' => '35', 'name' => 'KABUPATEN PACITAN', 'created_by' => '1'],
            ['id' => '3502', 'parent' => '35', 'name' => 'KABUPATEN PONOROGO', 'created_by' => '1'],
            ['id' => '3503', 'parent' => '35', 'name' => 'KABUPATEN TRENGGALEK', 'created_by' => '1'],
            ['id' => '3504', 'parent' => '35', 'name' => 'KABUPATEN TULUNGAGUNG', 'created_by' => '1'],
            ['id' => '3505', 'parent' => '35', 'name' => 'KABUPATEN BLITAR', 'created_by' => '1'],
            ['id' => '3506', 'parent' => '35', 'name' => 'KABUPATEN KEDIRI', 'created_by' => '1'],
            ['id' => '3507', 'parent' => '35', 'name' => 'KABUPATEN MALANG', 'created_by' => '1'],
            ['id' => '3508', 'parent' => '35', 'name' => 'KABUPATEN LUMAJANG', 'created_by' => '1'],
            ['id' => '3509', 'parent' => '35', 'name' => 'KABUPATEN JEMBER', 'created_by' => '1'],
            ['id' => '3510', 'parent' => '35', 'name' => 'KABUPATEN BANYUWANGI', 'created_by' => '1'],
            ['id' => '3511', 'parent' => '35', 'name' => 'KABUPATEN BONDOWOSO', 'created_by' => '1'],
            ['id' => '3512', 'parent' => '35', 'name' => 'KABUPATEN SITUBONDO', 'created_by' => '1'],
            ['id' => '3513', 'parent' => '35', 'name' => 'KABUPATEN PROBOLINGGO', 'created_by' => '1'],
            ['id' => '3514', 'parent' => '35', 'name' => 'KABUPATEN PASURUAN', 'created_by' => '1'],
            ['id' => '3515', 'parent' => '35', 'name' => 'KABUPATEN SIDOARJO', 'created_by' => '1'],
            ['id' => '3516', 'parent' => '35', 'name' => 'KABUPATEN MOJOKERTO', 'created_by' => '1'],
            ['id' => '3517', 'parent' => '35', 'name' => 'KABUPATEN JOMBANG', 'created_by' => '1'],
            ['id' => '3518', 'parent' => '35', 'name' => 'KABUPATEN NGANJUK', 'created_by' => '1'],
            ['id' => '3519', 'parent' => '35', 'name' => 'KABUPATEN MADIUN', 'created_by' => '1'],
            ['id' => '3520', 'parent' => '35', 'name' => 'KABUPATEN MAGETAN', 'created_by' => '1'],
            ['id' => '3521', 'parent' => '35', 'name' => 'KABUPATEN NGAWI', 'created_by' => '1'],
            ['id' => '3522', 'parent' => '35', 'name' => 'KABUPATEN BOJONEGORO', 'created_by' => '1'],
            ['id' => '3523', 'parent' => '35', 'name' => 'KABUPATEN TUBAN', 'created_by' => '1'],
            ['id' => '3524', 'parent' => '35', 'name' => 'KABUPATEN LAMONGAN', 'created_by' => '1'],
            ['id' => '3525', 'parent' => '35', 'name' => 'KABUPATEN GRESIK', 'created_by' => '1'],
            ['id' => '3526', 'parent' => '35', 'name' => 'KABUPATEN BANGKALAN', 'created_by' => '1'],
            ['id' => '3527', 'parent' => '35', 'name' => 'KABUPATEN SAMPANG', 'created_by' => '1'],
            ['id' => '3528', 'parent' => '35', 'name' => 'KABUPATEN PAMEKASAN', 'created_by' => '1'],
            ['id' => '3529', 'parent' => '35', 'name' => 'KABUPATEN SUMENEP', 'created_by' => '1'],
            ['id' => '3571', 'parent' => '35', 'name' => 'KOTA KEDIRI', 'created_by' => '1'],
            ['id' => '3572', 'parent' => '35', 'name' => 'KOTA BLITAR', 'created_by' => '1'],
            ['id' => '3573', 'parent' => '35', 'name' => 'KOTA MALANG', 'created_by' => '1'],
            ['id' => '3574', 'parent' => '35', 'name' => 'KOTA PROBOLINGGO', 'created_by' => '1'],
            ['id' => '3575', 'parent' => '35', 'name' => 'KOTA PASURUAN', 'created_by' => '1'],
            ['id' => '3576', 'parent' => '35', 'name' => 'KOTA MOJOKERTO', 'created_by' => '1'],
            ['id' => '3577', 'parent' => '35', 'name' => 'KOTA MADIUN', 'created_by' => '1'],
            ['id' => '3578', 'parent' => '35', 'name' => 'KOTA SURABAYA', 'created_by' => '1'],
            ['id' => '3579', 'parent' => '35', 'name' => 'KOTA BATU', 'created_by' => '1'],
            ['id' => '3601', 'parent' => '36', 'name' => 'KABUPATEN PANDEGLANG', 'created_by' => '1'],
            ['id' => '3602', 'parent' => '36', 'name' => 'KABUPATEN LEBAK', 'created_by' => '1'],
            ['id' => '3603', 'parent' => '36', 'name' => 'KABUPATEN TANGERANG', 'created_by' => '1'],
            ['id' => '3604', 'parent' => '36', 'name' => 'KABUPATEN SERANG', 'created_by' => '1'],
            ['id' => '3671', 'parent' => '36', 'name' => 'KOTA TANGERANG', 'created_by' => '1'],
            ['id' => '3672', 'parent' => '36', 'name' => 'KOTA CILEGON', 'created_by' => '1'],
            ['id' => '3673', 'parent' => '36', 'name' => 'KOTA SERANG', 'created_by' => '1'],
            ['id' => '3674', 'parent' => '36', 'name' => 'KOTA TANGERANG SELATAN', 'created_by' => '1'],
            ['id' => '5101', 'parent' => '51', 'name' => 'KABUPATEN JEMBRANA', 'created_by' => '1'],
            ['id' => '5102', 'parent' => '51', 'name' => 'KABUPATEN TABANAN', 'created_by' => '1'],
            ['id' => '5103', 'parent' => '51', 'name' => 'KABUPATEN BADUNG', 'created_by' => '1'],
            ['id' => '5104', 'parent' => '51', 'name' => 'KABUPATEN GIANYAR', 'created_by' => '1'],
            ['id' => '5105', 'parent' => '51', 'name' => 'KABUPATEN KLUNGKUNG', 'created_by' => '1'],
            ['id' => '5106', 'parent' => '51', 'name' => 'KABUPATEN BANGLI', 'created_by' => '1'],
            ['id' => '5107', 'parent' => '51', 'name' => 'KABUPATEN KARANG ASEM', 'created_by' => '1'],
            ['id' => '5108', 'parent' => '51', 'name' => 'KABUPATEN BULELENG', 'created_by' => '1'],
            ['id' => '5171', 'parent' => '51', 'name' => 'KOTA DENPASAR', 'created_by' => '1'],
            ['id' => '5201', 'parent' => '52', 'name' => 'KABUPATEN LOMBOK BARAT', 'created_by' => '1'],
            ['id' => '5202', 'parent' => '52', 'name' => 'KABUPATEN LOMBOK TENGAH', 'created_by' => '1'],
            ['id' => '5203', 'parent' => '52', 'name' => 'KABUPATEN LOMBOK TIMUR', 'created_by' => '1'],
            ['id' => '5204', 'parent' => '52', 'name' => 'KABUPATEN SUMBAWA', 'created_by' => '1'],
            ['id' => '5205', 'parent' => '52', 'name' => 'KABUPATEN DOMPU', 'created_by' => '1'],
            ['id' => '5206', 'parent' => '52', 'name' => 'KABUPATEN BIMA', 'created_by' => '1'],
            ['id' => '5207', 'parent' => '52', 'name' => 'KABUPATEN SUMBAWA BARAT', 'created_by' => '1'],
            ['id' => '5208', 'parent' => '52', 'name' => 'KABUPATEN LOMBOK UTARA', 'created_by' => '1'],
            ['id' => '5271', 'parent' => '52', 'name' => 'KOTA MATARAM', 'created_by' => '1'],
            ['id' => '5272', 'parent' => '52', 'name' => 'KOTA BIMA', 'created_by' => '1'],
            ['id' => '5301', 'parent' => '53', 'name' => 'KABUPATEN SUMBA BARAT', 'created_by' => '1'],
            ['id' => '5302', 'parent' => '53', 'name' => 'KABUPATEN SUMBA TIMUR', 'created_by' => '1'],
            ['id' => '5303', 'parent' => '53', 'name' => 'KABUPATEN KUPANG', 'created_by' => '1'],
            ['id' => '5304', 'parent' => '53', 'name' => 'KABUPATEN TIMOR TENGAH SELATAN', 'created_by' => '1'],
            ['id' => '5305', 'parent' => '53', 'name' => 'KABUPATEN TIMOR TENGAH UTARA', 'created_by' => '1'],
            ['id' => '5306', 'parent' => '53', 'name' => 'KABUPATEN BELU', 'created_by' => '1'],
            ['id' => '5307', 'parent' => '53', 'name' => 'KABUPATEN ALOR', 'created_by' => '1'],
            ['id' => '5308', 'parent' => '53', 'name' => 'KABUPATEN LEMBATA', 'created_by' => '1'],
            ['id' => '5309', 'parent' => '53', 'name' => 'KABUPATEN FLORES TIMUR', 'created_by' => '1'],
            ['id' => '5310', 'parent' => '53', 'name' => 'KABUPATEN SIKKA', 'created_by' => '1'],
            ['id' => '5311', 'parent' => '53', 'name' => 'KABUPATEN ENDE', 'created_by' => '1'],
            ['id' => '5312', 'parent' => '53', 'name' => 'KABUPATEN NGADA', 'created_by' => '1'],
            ['id' => '5313', 'parent' => '53', 'name' => 'KABUPATEN MANGGARAI', 'created_by' => '1'],
            ['id' => '5314', 'parent' => '53', 'name' => 'KABUPATEN ROTE NDAO', 'created_by' => '1'],
            ['id' => '5315', 'parent' => '53', 'name' => 'KABUPATEN MANGGARAI BARAT', 'created_by' => '1'],
            ['id' => '5316', 'parent' => '53', 'name' => 'KABUPATEN SUMBA TENGAH', 'created_by' => '1'],
            ['id' => '5317', 'parent' => '53', 'name' => 'KABUPATEN SUMBA BARAT DAYA', 'created_by' => '1'],
            ['id' => '5318', 'parent' => '53', 'name' => 'KABUPATEN NAGEKEO', 'created_by' => '1'],
            ['id' => '5319', 'parent' => '53', 'name' => 'KABUPATEN MANGGARAI TIMUR', 'created_by' => '1'],
            ['id' => '5320', 'parent' => '53', 'name' => 'KABUPATEN SABU RAIJUA', 'created_by' => '1'],
            ['id' => '5321', 'parent' => '53', 'name' => 'KABUPATEN MALAKA', 'created_by' => '1'],
            ['id' => '5371', 'parent' => '53', 'name' => 'KOTA KUPANG', 'created_by' => '1'],
            ['id' => '5372', 'parent' => '53', 'name' => 'LABUAN BAJO', 'created_by' => '1'],
            ['id' => '6101', 'parent' => '61', 'name' => 'KABUPATEN SAMBAS', 'created_by' => '1'],
            ['id' => '6102', 'parent' => '61', 'name' => 'KABUPATEN BENGKAYANG', 'created_by' => '1'],
            ['id' => '6103', 'parent' => '61', 'name' => 'KABUPATEN LANDAK', 'created_by' => '1'],
            ['id' => '6104', 'parent' => '61', 'name' => 'KABUPATEN MEMPAWAH', 'created_by' => '1'],
            ['id' => '6105', 'parent' => '61', 'name' => 'KABUPATEN SANGGAU', 'created_by' => '1'],
            ['id' => '6106', 'parent' => '61', 'name' => 'KABUPATEN KETAPANG', 'created_by' => '1'],
            ['id' => '6107', 'parent' => '61', 'name' => 'KABUPATEN SINTANG', 'created_by' => '1'],
            ['id' => '6108', 'parent' => '61', 'name' => 'KABUPATEN KAPUAS HULU', 'created_by' => '1'],
            ['id' => '6109', 'parent' => '61', 'name' => 'KABUPATEN SEKADAU', 'created_by' => '1'],
            ['id' => '6110', 'parent' => '61', 'name' => 'KABUPATEN MELAWI', 'created_by' => '1'],
            ['id' => '6111', 'parent' => '61', 'name' => 'KABUPATEN KAYONG UTARA', 'created_by' => '1'],
            ['id' => '6112', 'parent' => '61', 'name' => 'KABUPATEN KUBU RAYA', 'created_by' => '1'],
            ['id' => '6171', 'parent' => '61', 'name' => 'KOTA PONTIANAK', 'created_by' => '1'],
            ['id' => '6172', 'parent' => '61', 'name' => 'KOTA SINGKAWANG', 'created_by' => '1'],
            ['id' => '6201', 'parent' => '62', 'name' => 'KABUPATEN KOTAWARINGIN BARAT', 'created_by' => '1'],
            ['id' => '6202', 'parent' => '62', 'name' => 'KABUPATEN KOTAWARINGIN TIMUR', 'created_by' => '1'],
            ['id' => '6203', 'parent' => '62', 'name' => 'KABUPATEN KAPUAS', 'created_by' => '1'],
            ['id' => '6204', 'parent' => '62', 'name' => 'KABUPATEN BARITO SELATAN', 'created_by' => '1'],
            ['id' => '6205', 'parent' => '62', 'name' => 'KABUPATEN BARITO UTARA', 'created_by' => '1'],
            ['id' => '6206', 'parent' => '62', 'name' => 'KABUPATEN SUKAMARA', 'created_by' => '1'],
            ['id' => '6207', 'parent' => '62', 'name' => 'KABUPATEN LAMANDAU', 'created_by' => '1'],
            ['id' => '6208', 'parent' => '62', 'name' => 'KABUPATEN SERUYAN', 'created_by' => '1'],
            ['id' => '6209', 'parent' => '62', 'name' => 'KABUPATEN KATINGAN', 'created_by' => '1'],
            ['id' => '6210', 'parent' => '62', 'name' => 'KABUPATEN PULANG PISAU', 'created_by' => '1'],
            ['id' => '6211', 'parent' => '62', 'name' => 'KABUPATEN GUNUNG MAS', 'created_by' => '1'],
            ['id' => '6212', 'parent' => '62', 'name' => 'KABUPATEN BARITO TIMUR', 'created_by' => '1'],
            ['id' => '6213', 'parent' => '62', 'name' => 'KABUPATEN MURUNG RAYA', 'created_by' => '1'],
            ['id' => '6271', 'parent' => '62', 'name' => 'KOTA PALANGKA RAYA', 'created_by' => '1'],
            ['id' => '6301', 'parent' => '63', 'name' => 'KABUPATEN TANAH LAUT', 'created_by' => '1'],
            ['id' => '6302', 'parent' => '63', 'name' => 'KABUPATEN KOTA BARU', 'created_by' => '1'],
            ['id' => '6303', 'parent' => '63', 'name' => 'KABUPATEN BANJAR', 'created_by' => '1'],
            ['id' => '6304', 'parent' => '63', 'name' => 'KABUPATEN BARITO KUALA', 'created_by' => '1'],
            ['id' => '6305', 'parent' => '63', 'name' => 'KABUPATEN TAPIN', 'created_by' => '1'],
            ['id' => '6306', 'parent' => '63', 'name' => 'KABUPATEN HULU SUNGAI SELATAN', 'created_by' => '1'],
            ['id' => '6307', 'parent' => '63', 'name' => 'KABUPATEN HULU SUNGAI TENGAH', 'created_by' => '1'],
            ['id' => '6308', 'parent' => '63', 'name' => 'KABUPATEN HULU SUNGAI UTARA', 'created_by' => '1'],
            ['id' => '6309', 'parent' => '63', 'name' => 'KABUPATEN TABALONG', 'created_by' => '1'],
            ['id' => '6310', 'parent' => '63', 'name' => 'KABUPATEN TANAH BUMBU', 'created_by' => '1'],
            ['id' => '6311', 'parent' => '63', 'name' => 'KABUPATEN BALANGAN', 'created_by' => '1'],
            ['id' => '6371', 'parent' => '63', 'name' => 'KOTA BANJARMASIN', 'created_by' => '1'],
            ['id' => '6372', 'parent' => '63', 'name' => 'KOTA BANJAR BARU', 'created_by' => '1'],
            ['id' => '6401', 'parent' => '64', 'name' => 'KABUPATEN PASER', 'created_by' => '1'],
            ['id' => '6402', 'parent' => '64', 'name' => 'KABUPATEN KUTAI BARAT', 'created_by' => '1'],
            ['id' => '6403', 'parent' => '64', 'name' => 'KABUPATEN KUTAI KARTANEGARA', 'created_by' => '1'],
            ['id' => '6404', 'parent' => '64', 'name' => 'KABUPATEN KUTAI TIMUR', 'created_by' => '1'],
            ['id' => '6405', 'parent' => '64', 'name' => 'KABUPATEN BERAU', 'created_by' => '1'],
            ['id' => '6409', 'parent' => '64', 'name' => 'KABUPATEN PENAJAM PASER UTARA', 'created_by' => '1'],
            ['id' => '6411', 'parent' => '64', 'name' => 'KABUPATEN MAHAKAM HULU', 'created_by' => '1'],
            ['id' => '6471', 'parent' => '64', 'name' => 'KOTA BALIKPAPAN', 'created_by' => '1'],
            ['id' => '6472', 'parent' => '64', 'name' => 'KOTA SAMARINDA', 'created_by' => '1'],
            ['id' => '6474', 'parent' => '64', 'name' => 'KOTA BONTANG', 'created_by' => '1'],
            ['id' => '6475', 'parent' => '64', 'name' => 'SANGATA', 'created_by' => '1'],
            ['id' => '6476', 'parent' => '64', 'name' => 'SENDAWAR', 'created_by' => '1'],
            ['id' => '6477', 'parent' => '64', 'name' => 'PANAJAM', 'created_by' => '1'],
            ['id' => '6478', 'parent' => '64', 'name' => 'TANJUNG ARU', 'created_by' => '1'],
            ['id' => '6482', 'parent' => '64', 'name' => 'LONGKALI', 'created_by' => '1'],
            ['id' => '6484', 'parent' => '64', 'name' => 'BATU KAJANG', 'created_by' => '1'],
            ['id' => '6501', 'parent' => '65', 'name' => 'KABUPATEN MALINAU', 'created_by' => '1'],
            ['id' => '6502', 'parent' => '65', 'name' => 'KABUPATEN BULUNGAN', 'created_by' => '1'],
            ['id' => '6503', 'parent' => '65', 'name' => 'KABUPATEN TANA TIDUNG', 'created_by' => '1'],
            ['id' => '6504', 'parent' => '65', 'name' => 'KABUPATEN NUNUKAN', 'created_by' => '1'],
            ['id' => '6571', 'parent' => '65', 'name' => 'KOTA TARAKAN', 'created_by' => '1'],
            ['id' => '7101', 'parent' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW', 'created_by' => '1'],
            ['id' => '7102', 'parent' => '71', 'name' => 'KABUPATEN MINAHASA', 'created_by' => '1'],
            ['id' => '7103', 'parent' => '71', 'name' => 'KABUPATEN KEPULAUAN SANGIHE', 'created_by' => '1'],
            ['id' => '7104', 'parent' => '71', 'name' => 'KABUPATEN KEPULAUAN TALAUD', 'created_by' => '1'],
            ['id' => '7105', 'parent' => '71', 'name' => 'KABUPATEN MINAHASA SELATAN', 'created_by' => '1'],
            ['id' => '7106', 'parent' => '71', 'name' => 'KABUPATEN MINAHASA UTARA', 'created_by' => '1'],
            ['id' => '7107', 'parent' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'created_by' => '1'],
            ['id' => '7108', 'parent' => '71', 'name' => 'KABUPATEN SIAU TAGULANDANG BIARO', 'created_by' => '1'],
            ['id' => '7109', 'parent' => '71', 'name' => 'KABUPATEN MINAHASA TENGGARA', 'created_by' => '1'],
            ['id' => '7110', 'parent' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'created_by' => '1'],
            ['id' => '7111', 'parent' => '71', 'name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'created_by' => '1'],
            ['id' => '7171', 'parent' => '71', 'name' => 'KOTA MANADO', 'created_by' => '1'],
            ['id' => '7172', 'parent' => '71', 'name' => 'KOTA BITUNG', 'created_by' => '1'],
            ['id' => '7173', 'parent' => '71', 'name' => 'KOTA TOMOHON', 'created_by' => '1'],
            ['id' => '7174', 'parent' => '71', 'name' => 'KOTA KOTAMOBAGU', 'created_by' => '1'],
            ['id' => '7201', 'parent' => '72', 'name' => 'KABUPATEN BANGGAI KEPULAUAN', 'created_by' => '1'],
            ['id' => '7202', 'parent' => '72', 'name' => 'KABUPATEN BANGGAI', 'created_by' => '1'],
            ['id' => '7203', 'parent' => '72', 'name' => 'KABUPATEN MOROWALI', 'created_by' => '1'],
            ['id' => '7204', 'parent' => '72', 'name' => 'KABUPATEN POSO', 'created_by' => '1'],
            ['id' => '7205', 'parent' => '72', 'name' => 'KABUPATEN DONGGALA', 'created_by' => '1'],
            ['id' => '7206', 'parent' => '72', 'name' => 'KABUPATEN TOLI-TOLI', 'created_by' => '1'],
            ['id' => '7207', 'parent' => '72', 'name' => 'KABUPATEN BUOL', 'created_by' => '1'],
            ['id' => '7208', 'parent' => '72', 'name' => 'KABUPATEN PARIGI MOUTONG', 'created_by' => '1'],
            ['id' => '7209', 'parent' => '72', 'name' => 'KABUPATEN TOJO UNA-UNA', 'created_by' => '1'],
            ['id' => '7210', 'parent' => '72', 'name' => 'KABUPATEN SIGI', 'created_by' => '1'],
            ['id' => '7211', 'parent' => '72', 'name' => 'KABUPATEN BANGGAI LAUT', 'created_by' => '1'],
            ['id' => '7212', 'parent' => '72', 'name' => 'KABUPATEN MOROWALI UTARA', 'created_by' => '1'],
            ['id' => '7271', 'parent' => '72', 'name' => 'KOTA PALU', 'created_by' => '1'],
            ['id' => '7301', 'parent' => '73', 'name' => 'KABUPATEN KEPULAUAN SELAYAR', 'created_by' => '1'],
            ['id' => '7302', 'parent' => '73', 'name' => 'KABUPATEN BULUKUMBA', 'created_by' => '1'],
            ['id' => '7303', 'parent' => '73', 'name' => 'KABUPATEN BANTAENG', 'created_by' => '1'],
            ['id' => '7304', 'parent' => '73', 'name' => 'KABUPATEN JENEPONTO', 'created_by' => '1'],
            ['id' => '7305', 'parent' => '73', 'name' => 'KABUPATEN TAKALAR', 'created_by' => '1'],
            ['id' => '7306', 'parent' => '73', 'name' => 'KABUPATEN GOWA', 'created_by' => '1'],
            ['id' => '7307', 'parent' => '73', 'name' => 'KABUPATEN SINJAI', 'created_by' => '1'],
            ['id' => '7308', 'parent' => '73', 'name' => 'KABUPATEN MAROS', 'created_by' => '1'],
            ['id' => '7309', 'parent' => '73', 'name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'created_by' => '1'],
            ['id' => '7310', 'parent' => '73', 'name' => 'KABUPATEN BARRU', 'created_by' => '1'],
            ['id' => '7311', 'parent' => '73', 'name' => 'KABUPATEN BONE', 'created_by' => '1'],
            ['id' => '7312', 'parent' => '73', 'name' => 'KABUPATEN SOPPENG', 'created_by' => '1'],
            ['id' => '7313', 'parent' => '73', 'name' => 'KABUPATEN WAJO', 'created_by' => '1'],
            ['id' => '7314', 'parent' => '73', 'name' => 'KABUPATEN SIDENRENG RAPPANG', 'created_by' => '1'],
            ['id' => '7315', 'parent' => '73', 'name' => 'KABUPATEN PINRANG', 'created_by' => '1'],
            ['id' => '7316', 'parent' => '73', 'name' => 'KABUPATEN ENREKANG', 'created_by' => '1'],
            ['id' => '7317', 'parent' => '73', 'name' => 'KABUPATEN LUWU', 'created_by' => '1'],
            ['id' => '7318', 'parent' => '73', 'name' => 'KABUPATEN TANA TORAJA', 'created_by' => '1'],
            ['id' => '7322', 'parent' => '73', 'name' => 'KABUPATEN LUWU UTARA', 'created_by' => '1'],
            ['id' => '7325', 'parent' => '73', 'name' => 'KABUPATEN LUWU TIMUR', 'created_by' => '1'],
            ['id' => '7326', 'parent' => '73', 'name' => 'KABUPATEN TORAJA UTARA', 'created_by' => '1'],
            ['id' => '7371', 'parent' => '73', 'name' => 'KOTA MAKASSAR', 'created_by' => '1'],
            ['id' => '7372', 'parent' => '73', 'name' => 'KOTA PAREPARE', 'created_by' => '1'],
            ['id' => '7373', 'parent' => '73', 'name' => 'KOTA PALOPO', 'created_by' => '1'],
            ['id' => '7401', 'parent' => '74', 'name' => 'KABUPATEN BUTON', 'created_by' => '1'],
            ['id' => '7402', 'parent' => '74', 'name' => 'KABUPATEN MUNA', 'created_by' => '1'],
            ['id' => '7403', 'parent' => '74', 'name' => 'KABUPATEN KONAWE', 'created_by' => '1'],
            ['id' => '7404', 'parent' => '74', 'name' => 'KABUPATEN KOLAKA', 'created_by' => '1'],
            ['id' => '7405', 'parent' => '74', 'name' => 'KABUPATEN KONAWE SELATAN', 'created_by' => '1'],
            ['id' => '7406', 'parent' => '74', 'name' => 'KABUPATEN BOMBANA', 'created_by' => '1'],
            ['id' => '7407', 'parent' => '74', 'name' => 'KABUPATEN WAKATOBI', 'created_by' => '1'],
            ['id' => '7408', 'parent' => '74', 'name' => 'KABUPATEN KOLAKA UTARA', 'created_by' => '1'],
            ['id' => '7409', 'parent' => '74', 'name' => 'KABUPATEN BUTON UTARA', 'created_by' => '1'],
            ['id' => '7410', 'parent' => '74', 'name' => 'KABUPATEN KONAWE UTARA', 'created_by' => '1'],
            ['id' => '7411', 'parent' => '74', 'name' => 'KABUPATEN KOLAKA TIMUR', 'created_by' => '1'],
            ['id' => '7412', 'parent' => '74', 'name' => 'KABUPATEN KONAWE KEPULAUAN', 'created_by' => '1'],
            ['id' => '7413', 'parent' => '74', 'name' => 'KABUPATEN MUNA BARAT', 'created_by' => '1'],
            ['id' => '7414', 'parent' => '74', 'name' => 'KABUPATEN BUTON TENGAH', 'created_by' => '1'],
            ['id' => '7415', 'parent' => '74', 'name' => 'KABUPATEN BUTON SELATAN', 'created_by' => '1'],
            ['id' => '7471', 'parent' => '74', 'name' => 'KOTA KENDARI', 'created_by' => '1'],
            ['id' => '7472', 'parent' => '74', 'name' => 'KOTA BAUBAU', 'created_by' => '1'],
            ['id' => '7501', 'parent' => '75', 'name' => 'KABUPATEN BOALEMO', 'created_by' => '1'],
            ['id' => '7502', 'parent' => '75', 'name' => 'KABUPATEN GORONTALO', 'created_by' => '1'],
            ['id' => '7503', 'parent' => '75', 'name' => 'KABUPATEN POHUWATO', 'created_by' => '1'],
            ['id' => '7504', 'parent' => '75', 'name' => 'KABUPATEN BONE BOLANGO', 'created_by' => '1'],
            ['id' => '7505', 'parent' => '75', 'name' => 'KABUPATEN GORONTALO UTARA', 'created_by' => '1'],
            ['id' => '7571', 'parent' => '75', 'name' => 'KOTA GORONTALO', 'created_by' => '1'],
            ['id' => '7601', 'parent' => '76', 'name' => 'KABUPATEN MAJENE', 'created_by' => '1'],
            ['id' => '7602', 'parent' => '76', 'name' => 'KABUPATEN POLEWALI MANDAR', 'created_by' => '1'],
            ['id' => '7603', 'parent' => '76', 'name' => 'KABUPATEN MAMASA', 'created_by' => '1'],
            ['id' => '7604', 'parent' => '76', 'name' => 'KABUPATEN MAMUJU', 'created_by' => '1'],
            ['id' => '7605', 'parent' => '76', 'name' => 'KABUPATEN MAMUJU UTARA', 'created_by' => '1'],
            ['id' => '7606', 'parent' => '76', 'name' => 'KABUPATEN MAMUJU TENGAH', 'created_by' => '1'],
            ['id' => '8101', 'parent' => '81', 'name' => 'KABUPATEN MALUKU TENGGARA BARAT', 'created_by' => '1'],
            ['id' => '8102', 'parent' => '81', 'name' => 'KABUPATEN MALUKU TENGGARA', 'created_by' => '1'],
            ['id' => '8103', 'parent' => '81', 'name' => 'KABUPATEN MALUKU TENGAH', 'created_by' => '1'],
            ['id' => '8104', 'parent' => '81', 'name' => 'KABUPATEN BURU', 'created_by' => '1'],
            ['id' => '8105', 'parent' => '81', 'name' => 'KABUPATEN KEPULAUAN ARU', 'created_by' => '1'],
            ['id' => '8106', 'parent' => '81', 'name' => 'KABUPATEN SERAM BAGIAN BARAT', 'created_by' => '1'],
            ['id' => '8107', 'parent' => '81', 'name' => 'KABUPATEN SERAM BAGIAN TIMUR', 'created_by' => '1'],
            ['id' => '8108', 'parent' => '81', 'name' => 'KABUPATEN MALUKU BARAT DAYA', 'created_by' => '1'],
            ['id' => '8109', 'parent' => '81', 'name' => 'KABUPATEN BURU SELATAN', 'created_by' => '1'],
            ['id' => '8171', 'parent' => '81', 'name' => 'KOTA AMBON', 'created_by' => '1'],
            ['id' => '8172', 'parent' => '81', 'name' => 'KOTA TUAL', 'created_by' => '1'],
            ['id' => '8201', 'parent' => '82', 'name' => 'KABUPATEN HALMAHERA BARAT', 'created_by' => '1'],
            ['id' => '8202', 'parent' => '82', 'name' => 'KABUPATEN HALMAHERA TENGAH', 'created_by' => '1'],
            ['id' => '8203', 'parent' => '82', 'name' => 'KABUPATEN KEPULAUAN SULA', 'created_by' => '1'],
            ['id' => '8204', 'parent' => '82', 'name' => 'KABUPATEN HALMAHERA SELATAN', 'created_by' => '1'],
            ['id' => '8205', 'parent' => '82', 'name' => 'KABUPATEN HALMAHERA UTARA', 'created_by' => '1'],
            ['id' => '8206', 'parent' => '82', 'name' => 'KABUPATEN HALMAHERA TIMUR', 'created_by' => '1'],
            ['id' => '8207', 'parent' => '82', 'name' => 'KABUPATEN PULAU MOROTAI', 'created_by' => '1'],
            ['id' => '8208', 'parent' => '82', 'name' => 'KABUPATEN PULAU TALIABU', 'created_by' => '1'],
            ['id' => '8271', 'parent' => '82', 'name' => 'KOTA TERNATE', 'created_by' => '1'],
            ['id' => '8272', 'parent' => '82', 'name' => 'KOTA TIDORE KEPULAUAN', 'created_by' => '1'],
            ['id' => '9101', 'parent' => '91', 'name' => 'KABUPATEN FAKFAK', 'created_by' => '1'],
            ['id' => '9102', 'parent' => '91', 'name' => 'KABUPATEN KAIMANA', 'created_by' => '1'],
            ['id' => '9103', 'parent' => '91', 'name' => 'KABUPATEN TELUK WONDAMA', 'created_by' => '1'],
            ['id' => '9104', 'parent' => '91', 'name' => 'KABUPATEN TELUK BINTUNI', 'created_by' => '1'],
            ['id' => '9105', 'parent' => '91', 'name' => 'KABUPATEN MANOKWARI', 'created_by' => '1'],
            ['id' => '9106', 'parent' => '91', 'name' => 'KABUPATEN SORONG SELATAN', 'created_by' => '1'],
            ['id' => '9107', 'parent' => '91', 'name' => 'KABUPATEN SORONG', 'created_by' => '1'],
            ['id' => '9108', 'parent' => '91', 'name' => 'KABUPATEN RAJA AMPAT', 'created_by' => '1'],
            ['id' => '9109', 'parent' => '91', 'name' => 'KABUPATEN TAMBRAUW', 'created_by' => '1'],
            ['id' => '9110', 'parent' => '91', 'name' => 'KABUPATEN MAYBRAT', 'created_by' => '1'],
            ['id' => '9111', 'parent' => '91', 'name' => 'KABUPATEN MANOKWARI SELATAN', 'created_by' => '1'],
            ['id' => '9112', 'parent' => '91', 'name' => 'KABUPATEN PEGUNUNGAN ARFAK', 'created_by' => '1'],
            ['id' => '9171', 'parent' => '91', 'name' => 'KOTA SORONG', 'created_by' => '1'],
            ['id' => '9181', 'parent' => '91', 'name' => 'KOTA SERUI', 'created_by' => '1'],
            ['id' => '9191', 'parent' => '91', 'name' => 'TIMIKA', 'created_by' => '1'],
            ['id' => '9401', 'parent' => '94', 'name' => 'KABUPATEN MERAUKE', 'created_by' => '1'],
            ['id' => '9402', 'parent' => '94', 'name' => 'KABUPATEN JAYAWIJAYA', 'created_by' => '1'],
            ['id' => '9403', 'parent' => '94', 'name' => 'KABUPATEN JAYAPURA', 'created_by' => '1'],
            ['id' => '9404', 'parent' => '94', 'name' => 'KABUPATEN NABIRE', 'created_by' => '1'],
            ['id' => '9408', 'parent' => '94', 'name' => 'KABUPATEN KEPULAUAN YAPEN', 'created_by' => '1'],
            ['id' => '9409', 'parent' => '94', 'name' => 'KABUPATEN BIAK NUMFOR', 'created_by' => '1'],
            ['id' => '9410', 'parent' => '94', 'name' => 'KABUPATEN PANIAI', 'created_by' => '1'],
            ['id' => '9411', 'parent' => '94', 'name' => 'KABUPATEN PUNCAK JAYA', 'created_by' => '1'],
            ['id' => '9412', 'parent' => '94', 'name' => 'KABUPATEN MIMIKA', 'created_by' => '1'],
            ['id' => '9413', 'parent' => '94', 'name' => 'KABUPATEN BOVEN DIGOEL', 'created_by' => '1'],
            ['id' => '9414', 'parent' => '94', 'name' => 'KABUPATEN MAPPI', 'created_by' => '1'],
            ['id' => '9415', 'parent' => '94', 'name' => 'KABUPATEN ASMAT', 'created_by' => '1'],
            ['id' => '9416', 'parent' => '94', 'name' => 'KABUPATEN YAHUKIMO', 'created_by' => '1'],
            ['id' => '9417', 'parent' => '94', 'name' => 'KABUPATEN PEGUNUNGAN BINTANG', 'created_by' => '1'],
            ['id' => '9418', 'parent' => '94', 'name' => 'KABUPATEN TOLIKARA', 'created_by' => '1'],
            ['id' => '9419', 'parent' => '94', 'name' => 'KABUPATEN SARMI', 'created_by' => '1'],
            ['id' => '9420', 'parent' => '94', 'name' => 'KABUPATEN KEEROM', 'created_by' => '1'],
            ['id' => '9426', 'parent' => '94', 'name' => 'KABUPATEN WAROPEN', 'created_by' => '1'],
            ['id' => '9427', 'parent' => '94', 'name' => 'KABUPATEN SUPIORI', 'created_by' => '1'],
            ['id' => '9428', 'parent' => '94', 'name' => 'KABUPATEN MAMBERAMO RAYA', 'created_by' => '1'],
            ['id' => '9429', 'parent' => '94', 'name' => 'KABUPATEN NDUGA', 'created_by' => '1'],
            ['id' => '9430', 'parent' => '94', 'name' => 'KABUPATEN LANNY JAYA', 'created_by' => '1'],
            ['id' => '9431', 'parent' => '94', 'name' => 'KABUPATEN MAMBERAMO TENGAH', 'created_by' => '1'],
            ['id' => '9432', 'parent' => '94', 'name' => 'KABUPATEN YALIMO', 'created_by' => '1'],
            ['id' => '9433', 'parent' => '94', 'name' => 'KABUPATEN PUNCAK', 'created_by' => '1'],
            ['id' => '9434', 'parent' => '94', 'name' => 'KABUPATEN DOGIYAI', 'created_by' => '1'],
            ['id' => '9435', 'parent' => '94', 'name' => 'KABUPATEN INTAN JAYA', 'created_by' => '1'],
            ['id' => '9436', 'parent' => '94', 'name' => 'KABUPATEN DEIYAI', 'created_by' => '1'],
            ['id' => '9471', 'parent' => '94', 'name' => 'KOTA JAYAPURA', 'created_by' => '1'],
        ];

        foreach ($data as $key => $value) {
            $record = Regions::firstOrNew(
                [
                    'id'    => $value['id']
                ]
            );
            $record->fill($value);
            $record->save();
        }
    }
}
